### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by stevetoro** [jeromyiacton/prj-rev-bwfs-dasmoto#4]
https://github.com/jeromyiacton/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/style.css#L14-L36

You're repeating _a lot_ of styles that the different item sections share. Consider putting the shared styles into a single CSS rule and then putting the unique styles into separate CSS rules.

```css
h2 {
  font-size:32px;
  font-weight:bold;
  color:white;
}

.brushes{
  background-color:mediumspringgreen;
}

.frames{
  background-color:lightcoral;
}

.paint{
  background-color:skyblue;
}
```

Notice I also don't need to specify the font-family at all since it's already specified by the `html` selector rule.

**Don't. Repeat. Yourself.**
